INSERT INTO COUNTRIES (CODE, NAME) VALUES ('CH', 'Switzerland');
INSERT INTO COUNTRIES (CODE, NAME) VALUES ('GR', 'England');
INSERT INTO COUNTRIES (CODE, NAME) VALUES ('IT', 'Italy');
INSERT INTO COUNTRIES (CODE, NAME) VALUES ('SW', 'Sweden');
INSERT INTO COUNTRIES (CODE, NAME) VALUES ('SZ', 'Swaziland');
